version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: doctordiesel/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: doctordiesel/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: doctordiesel/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media/
    ports:
      - 9000:80
    depends_on:
      - backend